---

- name: MySQL installation script has run (Debian-based distros).
  include_tasks: install-debian.yml
  when: os_family == "Ubuntu/Debian"

- name: mysql_secure_installation has been run.
  include_tasks: secure.yml

- name: MySQL has been enabled on start-up & started.
  service:
    enabled: yes
    state: started
    name: mysql
